### ISSUE TITLE
AttributeError: 'OktaAuthConfig'

### ISSUE THREAD

**Issue by lmechtaoui** [jmhale/okta-awscli#148]
Hello, 
I'm trying to implement an okta authentification to get an aws access by CLI. but I'm getting this error :

DEBUG - Selected app: Amazon Web Services
Traceback (most recent call last):
  File "C:\Users\lmechtaoui\AppData\Local\Programs\Python\Python35\Scripts\okta-awscli-script.py", line 33, in <module>
    sys.exit(load_entry_point('okta-awscli==0.4.5', 'console_scripts', 'okta-awscli')())
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\oktaawscli\okta_awscli.py", line 121, in main
    aws_auth, okta_profile, profile, verbose, logger, token, cache, refresh_role, okta_username, okta_password
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\oktaawscli\okta_awscli.py", line 23, in get_credentials
    _, assertion = okta.get_assertion()
  File "c:\users\lmechtaoui\appdata\local\programs\python\python35\lib\site-packages\oktaawscli\okta_auth.py", line 156, in get_assertion
    self.okta_auth_config.save_chosen_app_link_for_profile(self.okta_profile, self.app_link)
AttributeError: 'OktaAuthConfig' object has no attribute 'save_chosen_app_link_for_profile'

Is there something wrong with my setup ? python version ? 
thanks

**Comment by avihaycloudinary** [comment]
Me2 :)

**Comment by jmhale** [comment]
@lmechtaoui @avihaycloudinary I know what's going on here. Fix coming shortly.

**Comment by jmhale** [comment]
This is fixed in `v0.4.6`.

**Comment by saringit** [comment]
I am using 0.5.4 and still getting this error. Any suggestions

Traceback (most recent call last):
  File "C:\Python311\Scripts\okta-awscli-script.py", line 33, in <module>
    sys.exit(load_entry_point('okta-awscli==0.5.4', 'console_scripts', 'okta-awscli')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\oktaawscli\okta_awscli.py", line 141, in main
    get_credentials(
  File "C:\Python311\Lib\site-packages\oktaawscli\okta_awscli.py", line 36, in get_credentials
    _, assertion = okta.get_assertion()
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\oktaawscli\okta_auth.py", line 165, in get_assertion
    assertion = self.get_saml_assertion(resp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\oktaawscli\okta_auth.py", line 149, in get_saml_assertion
    self.logger.error("SAML assertion not valid: " + assertion)
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
